### PR TITLE
Friendships v1

### PR DESCRIPTION
**Pull request by kitpao**
In this branch we implemented the following changes:
- [x] Added friendship table
- [x] Declare relations between users and friendships
- [x] Declare methods for User model
- [x] Created corresponding tests for Friendships and Users

### CODE REVIEW

**Review by maelfosso — APPROVED** [review]
# Changes required :red_circle: 

Hello coders,

Nice introduction in this milestone.
Sorry, but there are some missed requirement that should be implemented.

1. Posts in the timeline should be the ones written by the users or one of his friends, as indicated [here](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/friends_timeline.png)

2. There should be a button to invite user to friendship on users list page and on single user page, as indicated [here](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/user_can_see_invite_buttton.png)

3. You should write test for each model and also write integration test for 

- log in
- log out
- posts
- comments
- likes
- friendship

4. Take a look at these chunks of code.
https://github.com/EdCrux/ror-social-scaffold/blob/803ffc95f08930345a08246aad7332a44b1cedde/app/views/layouts/application.html.erb#L21-L25
https://github.com/EdCrux/ror-social-scaffold/blob/803ffc95f08930345a08246aad7332a44b1cedde/app/views/layouts/application.html.erb#L27-L31
https://github.com/EdCrux/ror-social-scaffold/blob/803ffc95f08930345a08246aad7332a44b1cedde/app/views/layouts/application.html.erb#L32-L36
Such chunk of code are called **Logic in views** and are not allowed. Please, use **VIEW HELPERS** for handling that.

Kindly make the changes and submit a new code review request
Thanks

Mael FOSSO

**Comment by kitpao** [comment]
Hello @maelfosso, thank you for your review, I'm just a bit confussed. Most of the code you are reffering to, was already in the repo from microverse we should fork from, and the New instructions in the pathwright only had instructions for the friendships and user associations, that's why we didn't touch the rest of the code. Also, for the friendships in the interfaces, we thought we were going to be asked to do it in a future milestone since it says the next milestone would still be about optimizing our code for friendships, maybe the instructions in the pathwright for milestone 2 / 5 should specify to include the interface? Just so there is no confussion, maybe they got erased when they deprecated some of the milestones, thanks for your time

**Comment by maelfosso** [comment]
I can understand @kitpao but from the **Milestone 5: Friendships v1** (*Milestone 2 to 4 are deprecated*, but left there to guide you), it said **and all requested features for friendship**.
You work didn't take it in consideration.

Also, by reading the next milestone, you will have noticed that there are no instructions for a detailed work concerning the implementation of Friendship.

**Comment by kitpao** [comment]
Oh! It's easy to miss that line, thank you @maelfosso

**Comment by kitpao** [comment]
Changes required were done :)

**Review by euqueme — CHANGES_REQUESTED** [review]
> ### Pull Request reviewed by Maria Eugenia Queme P. (TSE)

### Hello @kitpao and @EdCrux :lollipop: :balloon: 

### Thank you for working on the changes requested by the previous reviewer :medal_sports: :medal_sports: you've done a great job so far I especially like you added test cases not only for the Friendship functionalities that were requested in this milestone but even for the original scaffold. there is only one thing to work on :construction_worker: :construction_worker_woman: 

#### Behaviour

- [x] User can reject a friendship request ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/accept_reject_friendship.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/))

- Let's add a button to be able to reject an unwanted friendship request

### That's it, team! :raised_hands: 

### Please :pray:  do the changes :technologist: :woman_technologist:  and submit back for a code review when you are done :memo: 

Happy Coding! :rocket: 

Any questions? please ask me on slack **@ Maru** :woman_technologist: 

PROJECT STATUS: REQUESTED CHANGES :traffic_light:

**Review by rOluochKe — APPROVED** [review]
Hello Team!
### Well done, you got right this time :clap: Congratulations :boom: :100: The milestone has been approved.
### Merge and submit the milestone. Good luck in the next one!
- Happy coding!

**Pull request merged**
